version: '3'
services:
  ## Database Container 
  database:
    container_name: mv-database
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./storage/database/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mvinicius
      MYSQL_DATABASE: mvinicius
      MYSQL_USER: root
      MYSQL_PASSWORD: mvinicius
  # Server Container 
  server:
    container_name: mv-server
    build: docker/build/server
    ports:
      - 8000:80
    depends_on:
      - database
    links: 
      - database
    working_dir: /var/www/html
    restart: always
    environment:
      APP_ENV: 'dev'
    volumes:
      - ./storage/server/:/var/www/html/
      - ./docker/config/php/php.ini:/etc/php/7.2/php.ini
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  # Client Container
  client:
    container_name: mv-client
    build: docker/build/client
    ports:
      - 4200:4200
      - 49153:49153
    links: 
      - server
    volumes:
      - ./storage/client/:/app
    working_dir: /app
    command: ["yarn", "start"]
volumes:
  database:
  server:
  client:
